# -*- coding: utf-8 -*-
"""LAB 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-rlsyIwH9czmhr3Dvy89orMAG-A8TIS

Develop and implement a program to execute the perceptron learning algorithm,
customized to train a single-layer perceptron for binary classification tasks. create a
robust algorithm that refines the model's weights iteratively, resulting in a proficient
single-layer perceptron capable of effectively handling binary classification
challenges.
"""

import numpy as np

class Perceptron:
    def __init__(self, lr=0.01, epochs=100):
        self.lr = lr                  # Learning rate
        self.epochs = epochs          # Number of training passes

    def fit(self, X, y):
        self.w = np.zeros(X.shape[1]) # Initialize weights
        self.b = 0.0                  # Initialize bias

        # Training loop
        for _ in range(self.epochs):
            for xi, target in zip(X, y):
                pred = self.predict(xi)        # Current prediction
                error = target - pred          # Calculate error
                self.w += self.lr * error * xi # Update weights
                self.b += self.lr * error      # Update bias

    def predict(self, x):
        # Weighted sum + step function for binary classification
        return 1 if (x @ self.w + self.b) >= 0 else 0


# -------- Example Usage --------
X_train = np.array([[2, 3], [1, 4], [3, 5], [4, 2]])  # Training inputs
y_train = np.array([0, 0, 1, 1])                      # Training labels

p = Perceptron(lr=0.01, epochs=100) # Create perceptron
p.fit(X_train, y_train)             # Train perceptron

new_point = np.array([2, 4])        # New input for testing
print(f"Prediction for {new_point}: {p.predict(new_point)}")