# -*- coding: utf-8 -*-
"""LAB 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDxv4BAZZzwrlsxy9qzWj48FJnP9zpMX

Develop a program to classify the MNIST Dataset using Convolution Neural Network
[CNN].
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
import matplotlib.pyplot as plt

# --- Load & preprocess ---
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.astype('float32')/255.0
x_test  = x_test.astype('float32')/255.0
x_train = x_train[..., None]     # shape -> (N,28,28,1)
x_test  = x_test[..., None]
y_train = to_categorical(y_train, 10)
y_test  = to_categorical(y_test, 10)

# --- Model: small CNN for MNIST ---
model = Sequential([
    Conv2D(32, 3, activation='relu', input_shape=(28,28,1)),
    MaxPooling2D(2), Dropout(0.25),
    Conv2D(64, 3, activation='relu'),
    MaxPooling2D(2), Dropout(0.25),
    Flatten(), Dense(128, activation='relu'), Dropout(0.5),
    Dense(10, activation='softmax')
])

# --- Compile, train, evaluate ---
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
hist = model.fit(x_train, y_train, validation_split=0.1, epochs=10, batch_size=128, verbose=2)
loss, acc = model.evaluate(x_test, y_test, verbose=2)
print(f"Test accuracy: {acc:.4f}")

# --- Plot accuracy & loss ---
plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
plt.plot(hist.history['accuracy'], label='train'); plt.plot(hist.history['val_accuracy'], label='val')
plt.title('Accuracy'); plt.xlabel('Epoch'); plt.legend(); plt.grid(True)

plt.subplot(1,2,2)
plt.plot(hist.history['loss'], label='train'); plt.plot(hist.history['val_loss'], label='val')
plt.title('Loss'); plt.xlabel('Epoch'); plt.legend(); plt.grid(True)
plt.tight_layout(); plt.show()

# --- Predict & show a few examples ---
preds = model.predict(x_test)
pred_labels = preds.argmax(axis=1)
true_labels = y_test.argmax(axis=1)

plt.figure(figsize=(8,3))
for i in range(6):
    plt.subplot(1,6,i+1); plt.axis('off')
    plt.imshow(x_test[i].squeeze(), cmap='gray')
    plt.title(f"P:{pred_labels[i]}\nT:{true_labels[i]}")
plt.show()