# -*- coding: utf-8 -*-
"""LAB 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzUpMiqk0KgGZPCuUWE-oFTmfR5jdhXt

Develop a GRU based term stock price prediction model for tickers in yahoo finance.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout
import yfinance as yf

# --- Fetch stock data (raw OHLCV) ---


data = yf.download('AAPL', '2010-01-01', '2023-01-01').sort_index()

# --- Select the 'Open' column from MultiIndex yfinance output ---
data = data[('Open', 'AAPL')].to_frame().rename(columns={('Open','AAPL'): 'Open'})

# --- Convert to numpy array ---
dataset = data.values

# --- Scale data to [0,1] ---
scaler = MinMaxScaler()
scaled = scaler.fit_transform(dataset)

# --- 80% training data split ---
train_len = int(len(dataset) * 0.80)
train_data = scaled[:train_len]

# --- Build 60–day sequences for training ---
x_train, y_train = [], []
for i in range(60, len(train_data)):
    x_train.append(train_data[i-60:i, 0])
    y_train.append(train_data[i, 0])

x_train, y_train = np.array(x_train), np.array(y_train)
x_train = x_train.reshape(x_train.shape[0], x_train.shape[1], 1)
 # (samples, timesteps, features)

# --- Build GRU model ---
model = Sequential([
    GRU(50, return_sequences=True, input_shape=(x_train.shape[1], 1)),
    Dropout(0.2),
    GRU(50, return_sequences=False),
    Dropout(0.2),
    Dense(25),
    Dense(1)
])
model.compile(optimizer='adam', loss='mean_squared_error')

# --- Train (1 epoch as in original) ---
model.fit(x_train, y_train, batch_size=1, epochs=1, verbose=1)

# --- Prepare test sequences and predict ---
test_data = scaled[train_len - 60:]
x_test = np.array([test_data[i - 60:i, 0] for i in range(60, len(test_data))])
x_test = x_test.reshape(x_test.shape[0], x_test.shape[1], 1)
preds = model.predict(x_test)
preds = scaler.inverse_transform(preds)              # invert scaling
y_test = dataset[train_len:]                         # true Open prices for test set

# --- Metrics ---
rmse = np.sqrt(mean_squared_error(y_test, preds))
mae  = mean_absolute_error(y_test, preds)
print(f'RMSE: {rmse:.4f}  MAE: {mae:.4f}')

# --- Prepare plot data ---
train = data[:train_len]
valid = data[train_len:].copy()
valid['Predictions'] = preds

# --- Plot predictions vs real data ---
plt.figure(figsize=(16,8))
plt.title("GRU Stock Price Prediction")
plt.plot(train['Open'], label='Train')
plt.plot(valid['Open'], label='Validation')
plt.plot(valid['Predictions'], label='Predictions')
plt.xlabel("Date"); plt.ylabel("Open Price ($)")
plt.legend(); plt.show()

# --- Show predicted prices ---
print(valid.tail())